frontend:
  app:
    name: frontend-variant
  helm:
    valuesFiles:
      - values-variant.yaml
  destination:
    name: in-cluster
    namespace: stack-variant

backend:
  app:
    name: backend-variant
  helm:
    valuesFiles:
      - values-variant.yaml
  destination:
    name: in-cluster
    namespace: stack
